# Generated by Django 3.1.4 on 2021-01-13 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
                ('usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_kpi', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=200)),
                ('kpi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_json', models.JSONField()),
                ('fecha', models.DateTimeField()),
                ('camara_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camaras.camara')),
            ],
        ),
    ]
